/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWebhooksRouteImport } from './routes/dashboard/webhooks'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPlaygroundRouteImport } from './routes/dashboard/playground'
import { Route as DashboardKeysRouteImport } from './routes/dashboard/keys'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard/history'
import { Route as DashboardSchedulesIndexRouteImport } from './routes/dashboard/schedules.index'
import { Route as DashboardSchedulesIdRouteImport } from './routes/dashboard/schedules.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlaygroundRoute = DashboardPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysRoute = DashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchedulesIndexRoute = DashboardSchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchedulesIdRoute = DashboardSchedulesIdRouteImport.update({
  id: '/schedules/$id',
  path: '/schedules/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/schedules/$id': typeof DashboardSchedulesIdRoute
  '/dashboard/schedules/': typeof DashboardSchedulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/schedules/$id': typeof DashboardSchedulesIdRoute
  '/dashboard/schedules': typeof DashboardSchedulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/schedules/$id': typeof DashboardSchedulesIdRoute
  '/dashboard/schedules/': typeof DashboardSchedulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/register'
    | '/dashboard/history'
    | '/dashboard/keys'
    | '/dashboard/playground'
    | '/dashboard/settings'
    | '/dashboard/webhooks'
    | '/dashboard/'
    | '/dashboard/schedules/$id'
    | '/dashboard/schedules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/login'
    | '/register'
    | '/dashboard/history'
    | '/dashboard/keys'
    | '/dashboard/playground'
    | '/dashboard/settings'
    | '/dashboard/webhooks'
    | '/dashboard'
    | '/dashboard/schedules/$id'
    | '/dashboard/schedules'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/login'
    | '/register'
    | '/dashboard/history'
    | '/dashboard/keys'
    | '/dashboard/playground'
    | '/dashboard/settings'
    | '/dashboard/webhooks'
    | '/dashboard/'
    | '/dashboard/schedules/$id'
    | '/dashboard/schedules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/webhooks': {
      id: '/dashboard/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof DashboardWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/playground': {
      id: '/dashboard/playground'
      path: '/playground'
      fullPath: '/dashboard/playground'
      preLoaderRoute: typeof DashboardPlaygroundRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys': {
      id: '/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof DashboardKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedules/': {
      id: '/dashboard/schedules/'
      path: '/schedules'
      fullPath: '/dashboard/schedules/'
      preLoaderRoute: typeof DashboardSchedulesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedules/$id': {
      id: '/dashboard/schedules/$id'
      path: '/schedules/$id'
      fullPath: '/dashboard/schedules/$id'
      preLoaderRoute: typeof DashboardSchedulesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardKeysRoute: typeof DashboardKeysRoute
  DashboardPlaygroundRoute: typeof DashboardPlaygroundRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSchedulesIdRoute: typeof DashboardSchedulesIdRoute
  DashboardSchedulesIndexRoute: typeof DashboardSchedulesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardKeysRoute: DashboardKeysRoute,
  DashboardPlaygroundRoute: DashboardPlaygroundRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSchedulesIdRoute: DashboardSchedulesIdRoute,
  DashboardSchedulesIndexRoute: DashboardSchedulesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
